/**
 * Re-export all types from the generated Supabase database types.
 * 
 * This file exists for backward compatibility with existing imports.
 * The canonical source is `@/lib/supabase/database.types.ts` which
 * is auto-generated by `npx supabase gen types typescript --local`.
 */

export * from './supabase/database.types';
